### ISSUE TITLE
如何可以确定我的nginx-http-concat模块编译进了我的nginx了？

### ISSUE THREAD

**Issue by zouzg** [alibaba/nginx-http-concat#30]
由于我的服务器(Linux)之前已经安装一个nginx，然后这次我把nginx的功能加入进来，但是我之前在我的Mac电脑配置的完全工作。但是在我的服务器上相同的配置就是不工作。所以我在想是不是nginx没有编译进入二进制文件啊。
- ./configure和make的时候都可以搜索到nginx-http-concat正确配置了。
- make install里面并没有发现什么nginx-http-concat的关键字

所以我的问题就是：如何可以确定我的nginx-http-concat模块编译进了我的nginx了？

**Comment by ifduyue** [comment]
`nginx -V` 
or 
`strings `which nginx` | grep ngx_http_concat`

**Comment by zouzg** [comment]
谢谢, 用您的命令查看显示都已经安装了。可以我的配置还是不成功，我自己再看看配置是不是有什么问题吧。

**Comment by zouzg** [comment]
终于找到原因了，原来是ngx_http_concat_module.c文件中33行：

``` c
ngx_string("application/x-javascript")
```

把它改成

``` c
ngx_string("application/javascript")
```

就可以工作了，但是为不知为什么此处是application/x-javascript而不是application/javascript呢？如果是application/x-javascript，那nginx还需要什么什么额外的配置呢？

**Comment by ifduyue** [comment]
see #21
