### ISSUE TITLE
【已解决】一直遇到400错误，合并请求的时候

### ISSUE THREAD

**Issue by ghost** [alibaba/nginx-http-concat#39]
用这个东西合并请求，遇到400 错误。排查了很久，

最后是没有在配置文件里加  include mime.types;

类似下面这样

 http {
    include mime.types;
}

贴出来，希望可以帮到其他人

**Comment by Froguard** [comment]
@iloveyo123u1 到底是需要加还是不需要加？

**Comment by ghost** [comment]
@Froguard   要加

**Comment by kaysonwu** [comment]
加了之后还是 400 有知道的吗？ 参考 #21
